---
# See https://pre-commit.com for more information
repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
      - id: pre-commit-update
        stages:
          - pre-commit
        args:
          - --dry-run
          - --exclude
          - gitlint

  # See https://pre-commit.com/hooks.html for more hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
          - --markdown-linebreak-ext=tf
      - id: end-of-file-fixer
      - id: check-yaml
        stages:
          - pre-commit
      - id: check-added-large-files
        stages:
          - pre-commit

  # See https://jorisroovers.com/gitlint for more information
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  # https://github.com/adrienverge/yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
        stages:
          - pre-commit
        args: [--format, parsable, --strict]

  # # https://github.com/koalaman/shellcheck-precommit
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.10.0
  #   hooks:
  #     - id: shellcheck
  # args: ["--severity=warning"]  # Optionally only show errors and warnings

  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 25.1.0
    hooks:
      - id: black
